### PR TITLE
Automated build and test

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
This adds automated building with Travis CI.

Also some light testing.  Programs in samples are disassembled and compared against their counterparts in the test directory.  One archive is listed and compared against the corresponding listing in test.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
@atsampson, since you're hacking this I invited you to be a collaborator.  My idea was to send you review requests, mostly as a FYI thing.

**Comment by atsampson** [comment]
Yep, absolutely; happy to be of help.

**Comment by atsampson** [comment]
Works for me! Some thoughts:

- The `clean` rule could remove the `.list` files too.

- You could make the test rules depend on the reference file.

- If you called the reference files for dis10 `foo.dasm`, where `foo` is the name of the input file, then you wouldn't need the special case for `atsign.tcp`, and you won't need to add another rule for your `rel` branch, etc.

- If you do `make check` and the comparison fails, it'll still leave the new output file in place, so `make check` again without changing anything will succeed. Write the output file to a temporary name first, then move it into place once the comparison succeeds? (Or use `|| {rm $@; exit 1}` or similar.)

So something like:

```
%.dasm: dis10 samples/% test/%.dasm
        ./dis10 samples/$* > $@.new
        cmp $@.new test/$@
        mv $@.new $@
```

?

**Comment by larsbrinkhoff** [comment]
Thanks, good points!  I'll address them.

**Pull request merged**
